# Generated by Django 3.2.7 on 2021-11-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211103_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_tree',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
